version: "3.9"
   
services:
  db:
    image: postgres:13
    volumes:
      - postgres_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=secret
    ports:
      - "5432:5432"
  redis:
    image: "redis:5.0.5-alpine"
    restart: always
    ports:
      - "63791:6379"
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_storage:/data
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: secret
    command: server --console-address ":9001" /data


volumes:
  minio_storage: {}
  postgres_db:
